### ISSUE TITLE
Polls not returning correct votes

### ISSUE THREAD

**Issue by Mar0xy** [transfem-org/transbox#7]
Rebased had a backend change which seems to have messed up polls counting for every app this would need to be reverted as well as the frontend needing to pull in a [MR from upstream](https://gitlab.com/soapbox-pub/soapbox/-/merge_requests/2245#cbd328dc2f06e8f38cfc632ecb47dee2e3d62385) most likely to fix the poll percent counter

**Comment by Insert5StarName** [comment]
needs to be fixed asap this basicly makes polls useless 
![image](https://github.com/transfem-org/transbox/assets/123300075/51fc0dc1-c9e2-4059-9ac2-1b7fcd488fe0)

**Comment by Insert5StarName** [comment]
335 Votes if only 11 People Voted seems kinda wrong
imma look in to how the backend counts votes
![image](https://github.com/transfem-org/transbox/assets/123300075/46348abd-1f8f-4362-970f-0d8faa3202de)

**Comment by Insert5StarName** [comment]
Votes seem to not federate correctly also edits dont federate correctly aswell 
![image](https://github.com/transfem-org/transbox/assets/123300075/a9b50e65-7536-4c9e-bcc3-c3c342e585b4)
![image](https://github.com/transfem-org/transbox/assets/123300075/83f3b92c-919a-43a9-8de2-5c95419c8dd7)

**Comment by Mar0xy** [comment]
> edits dont federate correctly aswell

This is actually a general fediverse issue and not a platform specific issue
